FROM python:3.6

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install postgresql-client -y

RUN mkdir /app
WORKDIR /app

# Install Python dependencies
ADD requirements requirements
RUN pip install -r requirements/local.txt

ADD . /app/
