# Generated by Django 2.0.8 on 2019-01-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64)),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('job_title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/speaker')),
                ('speaker_type', models.CharField(choices=[('n', 'Normal'), ('k', 'Keynote')], default='n', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
