# Generated by Django 2.0.8 on 2019-01-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='facebook',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='github',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='twitter',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
