# Generated by Django 2.0.8 on 2019-02-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['sort_position']},
        ),
        migrations.AlterModelOptions(
            name='sponsortype',
            options={'ordering': ['sort_position']},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sort_position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='sponsortype',
            name='sort_position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
