# Generated by Django 2.0.8 on 2019-02-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_sorting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
