# Generated by Django 2.0.8 on 2019-01-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event.', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='If provided, appears below the event title.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the event.')),
                ('start_time', models.TimeField(help_text='Start time of the event.')),
                ('end_time', models.TimeField(help_text='End time of the event.')),
                ('venue', models.CharField(blank=True, help_text='Room or venue where this event will be held.', max_length=255)),
                ('sort_position', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['sort_position'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Day 1 (February 24)', max_length=255)),
                ('tab_position', models.CharField(choices=[('lef', 'Left'), ('rig', 'Right')], default='lef', max_length=3, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule.ProgramSchedule'),
        ),
    ]
